name: Build and Run Projects

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-run:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 9 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore NuGet packages
      run: dotnet restore SZTE-Bsc_Szakdolgozat.sln

    - name: Build all projects
      run: dotnet build SZTE-Bsc_Szakdolgozat.sln --no-restore --configuration Release

    - name: Run AuthAPI to verify it starts
      run: dotnet run --project ./AuthAPI/AuthAPI.csproj --no-build --configuration Release
      timeout-minutes: 1
      continue-on-error: true

    - name: Run Szakdoga (frontend) to verify it starts
      run: dotnet run --project ./Szakdoga/Szakdoga.csproj --no-build --configuration Release
      timeout-minutes: 1
      continue-on-error: true
