name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 9 (Preview)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        dotnet-quality: preview

    - name: Install MAUI and platform workloads
      run: |
        dotnet workload install maui
        dotnet workload install android
        dotnet workload install ios
        dotnet workload install maccatalyst
        dotnet workload install wasm-tools

    - name: Restore dependencies
      run: dotnet restore Szakdoga.csproj

    - name: Build MAUI project
      run: dotnet build Szakdoga.csproj --configuration Release --no-restore
